name: Tests
permissions:
  contents: read
  issues: none
  pull-requests: none

on: [pull_request, workflow_dispatch]

jobs:
  build_packages:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        # Super slow on ubuntu-latest
        # os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Add WiX v3 to PATH
        shell: pwsh
        run: |
          $wixPath = "C:\Program Files (x86)\WiX Toolset v3.11\bin"
          if (!(Test-Path $wixPath)) {
            $wixPath = "C:\Program Files (x86)\WiX Toolset v3.14\bin"
          }
          if (!(Test-Path $wixPath)) {
            throw "WiX Toolset path not found on runner"
          }
          $wixPath | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          "WIX_BIN=$wixPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Verify WiX
        shell: pwsh
        run: |
          candle.exe -?
          light.exe -?

      - name: Create dummy changelog file
        working-directory: ./ReleaseBuilder
        run: echo "## Changed" > ./changelog-news.txt

      - name: Compile releases
        working-directory: ./ReleaseBuilder
        env:
          UPDATER_KEYFILE: ./testfile.key1
          WIX:
        run: dotnet run -- build debug --compile-only=false --git-stash-push=false --disable-docker-push=true --keep-builds=true --disable-authenticode=true --disable-signcode=true --disable-notarize-signing=true --disable-gpg-signing=true --disable-s3-upload=true --disable-github-upload=true --disable-update-server-reload=true --disable-discourse-announce=true --disable-clean-source=true --password=test1234 --version=2.0.0.99
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: duplicati-${{ matrix.os }}
          path: ./ReleaseBuilder/builds/
          retention-days: 5
  # Disabled, as a new test needs to be written for the new UI
  # selenium:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Selenium
  #       run: pipeline/selenium/test.sh
